//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanVien
    {
        public int Ma_nv { get; set; }
        public string Ho_ten { get; set; }
        public string Diachi { get; set; }
        public Nullable<bool> Gioi_tinh { get; set; }
        public string Chuc_vu { get; set; }
        public Nullable<System.DateTime> Ngay_sinh { get; set; }
    }
}
