//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class taiKhoan
    {
        public int stt { get; set; }
        public string TenNV { get; set; }
        public string Chuc_vu { get; set; }
        public string tenTK { get; set; }
        public string matkhau { get; set; }
    }
}
